### PR TITLE
Made the 'no file to download' page similar to the main page

### PR DESCRIPTION
**Pull request by BrianMwangi21**
Hi there,

I saw some enhancements made in the issue 1. The enhancement number 3.
I have made a few tweaks to the 'no file to download' page. The theme continues and it still functions. 

Thanks.

### CODE REVIEW

**Comment by josephernest** [comment]
Thanks for the pull request! As @coldes was the first, I suggest we use his design suggested in issue #1. Can you modify with (in one-line it's ok):

`<html><head><meta content="width=device-width, initial-scale=1.0" name="viewport"><style type="text/css">*{color:white;font-family:sans-serif;padding:0em;margin:0;cursor:pointer;-webkit-touch-callout:none;-webkit-user-select:none;-khtml-user-select:none;-moz-user-select:none;-ms-user-select:none;user-select:none}body{width:100%;top:0;position:absolute;background-color:#f90;height:100%;left:0}a{position:absolute;top:0;height:100%;text-align:center;width:100%;text-decoration:none;display:block}a div{position:relative;top:45%;height:auto;text-align:center;width:100%;font-size:2.5em;text-decoration:none}a span{font-size:70%}</style><title></title></head><body> <a href="./"><div>NO FILE UPLOADED YET<br /><span>CLICK TO RELOAD</span></div></a></body></html>`

and I'll merge it.

**Comment by BrianMwangi21** [comment]
Hi again, have changed the design to reflect the suggestion made by @coldes.

Thanks

**Comment by BrianMwangi21** [comment]
Sorry about that, I am trying to add a security feature to Yopp, the `unlink($thefilecode)` is part of the new algorithm. I'll push it as a new merge request

**Comment by josephernest** [comment]
Thanks. Maybe it would be interesting to separate this in two separate pull requests. Here is what I suggest, can we delete this one. Then you can do:
* 1 new PR with only the "no file uploaded" page design `echo ' ...';`.

* 1 new PR with the rest (security, etc.)

**Comment by josephernest** [comment]
I mean these changes should not be present: https://imgur.com/a/O4z0m

**Comment by josephernest** [comment]
I'll close this one, better to do a new PR with only the `echo ' '` line changed, and then another one for all the security features;

**Pull request closed without merging**
